post_show:
    path:     /show/{id}
    defaults: { _controller: AceBlogBundle:Post:show }

post_new:
    path:     /new
    defaults: { _controller: AceBlogBundle:Post:new }

post_create:
    path:     /create
    defaults: { _controller: AceBlogBundle:Post:create }
    requirements: { _method: post }

post_edit:
    path:     /edit/{id}
    defaults: { _controller: AceBlogBundle:Post:edit }

post_update:
    path:     /update/{id}
    defaults: { _controller: AceBlogBundle:Post:update }
    requirements: { _method: post|put }

post_delete:
    path:     /delete/{id}
    defaults: { _controller: AceBlogBundle:Post:delete }
    requirements: { _method: post|delete }
