post:
    path:  /
    defaults: { _controller: AceBlogBundle:Post:index }

users:
    path: /users
    defaults: { _controller: AceBlogBundle:User:index }

profile:
    path: /profile
    defaults: { _controller: AceBlogBundle:User:profile }

login:
    path:   /login
    defaults:  { _controller: AceBlogBundle:Security:login }

login_check:
    path:   /profile/login_check

logout:
    path:   /profile/logout
  
AceBlogBundle_post:
    resource: "@AceBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

AceBlogBundle_user:
    resource: "@AceBlogBundle/Resources/config/routing/user.yml"
    prefix:   /user

AceBlogBundle_comment:
    resource: "@AceBlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment